version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/SocialTripperDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_NEO4J_URI: bolt://neo4j:7687
      SPRING_NEO4J_AUTHENTICATION_USERNAME: neo4j
      SPRING_NEO4J_AUTHENTICATION_PASSWORD: neo-db-passwd
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: SocialTripperDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 20s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/neo-db-passwd
    healthcheck:
      test: ["CMD-SHELL", "echo 'match (n) return n LIMIT 1;' | cypher-shell -u neo4j -p neo-db-passwd"]
      interval: 10s
      timeout: 20s
      retries: 10
    volumes:
      - neo4j_data:/data

volumes:
  postgres_data:
  neo4j_data: