server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  application:
    name: social-tripper-rest-api
  datasource:
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
    url: jdbc:postgresql://localhost:5432/SocialTripperDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      #ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  neo4j:
    uri: "bolt://localhost:7687"
    authentication:
      username: "neo4j"
      password: "neo4j"
#  flyway:
#    enabled: true
#    locations: "classpath:db/migration"
#    baseline-on-migrate: true
