insert into locations_scopes (id, name) values (1, 'city'), (2, 'country');

insert into events_statuses (id, name) values
                                (1,'created'),
                                (2, 'in progress'),
                                (3, 'finished'),
                                (4, 'cancelled');

insert into activities (id, name) values
                                      (1, 'water'),
                                      (2, 'walking'),
                                      (3, 'sport'),
                                      (4, 'running'),
                                      (5, 'ride'),
                                      (6, 'hiking'),
                                      (7, 'camping');


insert into countries (name) values
                                 ('Andorra'),
                                 ('United Arab Emirates'),
                                 ('Afghanistan'),
                                 ('Antigua and Barbuda'),
                                 ('Anguilla'),
                                 ('Albania'),
                                 ('Armenia'),
                                 ('Angola'),
                                 ('Argentina'),
                                 ('American Samoa'),
                                 ('Austria'),
                                 ('Australia'),
                                 ('Aruba'),
                                 ('Åland Islands'),
                                 ('Azerbaijan'),
                                 ('Bosnia and Herzegovina'),
                                 ('Barbados'),
                                 ('Bangladesh'),
                                 ('Belgium'),
                                 ('Burkina Faso'),
                                 ('Bulgaria'),
                                 ('Bahrain'),
                                 ('Burundi'),
                                 ('Benin'),
                                 ('Saint Barthélemy'),
                                 ('Bermuda'),
                                 ('Brunei Darussalam'),
                                 ('Bolivia,'),
                                 ('Bonaire, Sint Eustatius, and Saba'),
                                 ('Brazil'),
                                 ('Bahamas'),
                                 ('Bhutan'),
                                 ('Botswana'),
                                 ('Belarus'),
                                 ('Belize'),
                                 ('Canada'),
                                 ('Cocos (Keeling) Islands'),
                                 ('Democratic Republic of the Congo'),
                                 ('Central African Republic'),
                                 ('Republic of the Congo'),
                                 ('Switzerland'),
                                 ('Côte d''Ivoire (Ivory Coast)'),
                                    ('Cook Islands'),
                                    ('Chile'),
                                    ('Cameroon'),
                                    ('China'),
                                    ('Colombia'),
                                    ('Costa Rica'),
                                    ('Cuba'),
                                    ('Cape Verde (now Cabo Verde)'),
                                    ('Curaçao'),
                                    ('Christmas Island'),
                                    ('Cyprus'),
                                    ('Czech Republic'),
                                    ('Germany'),
                                    ('Diego Garcia'),
                                    ('Djibouti'),
                                    ('Denmark'),
                                    ('Dominica'),
                                    ('Dominican Republic'),
                                    ('Algeria'),
                                    ('Ecuador'),
                                    ('Estonia'),
                                    ('Egypt'),
                                    ('Western Sahara'),
                                    ('Eritrea'),
                                    ('Spain'),
                                    ('Ethiopia'),
                                    ('Finland'),
                                    ('Fiji'),
                                    ('Falkland Islands'),
                                    ('Federated States of Micronesia'),
                                    ('Faroe Islands'),
                                    ('France'),
                                    ('Gabon'),
                                    ('United Kingdom'),
                                    ('Grenada'),
                                    ('Georgia'),
                                    ('French Guiana'),
                                    ('Guernsey'),
                                    ('Ghana'),
                                    ('Gibraltar'),
                                    ('Greenland'),
                                    ('Gambia'),
                                    ('Guinea'),
                                    ('Guadeloupe'),
                                    ('Equatorial Guinea'),
                                    ('Greece'),
                                    ('Guatemala'),
                                    ('Guam'),
                                    ('Guinea-Bissau'),
                                    ('Guyana'),
                                    ('Hong Kong'),
                                    ('Honduras'),
                                    ('Croatia'),
                                    ('Haiti'),
                                    ('Hungary'),
                                    ('Indonesia'),
                                    ('Ireland'),
                                    ('Israel'),
                                    ('Isle of Man'),
                                    ('India'),
                                    ('British Indian Ocean Territory'),
                                    ('Iraq'),
                                    ('Iran'),
                                    ('Iceland'),
                                    ('Italy'),
                                    ('Jersey'),
                                    ('Jamaica'),
                                    ('Jordan'),
                                    ('Japan'),
                                    ('Kenya'),
                                    ('Kyrgyzstan'),
                                    ('Cambodia'),
                                    ('Kiribati'),
                                    ('Comoros'),
                                    ('Saint Kitts and Nevis'),
                                    ('South Korea'),
                                    ('Kuwait'),
                                    ('Cayman Islands'),
                                    ('Kazakhstan'),
                                    ('Laos'),
                                    ('Lebanon'),
                                    ('Saint Lucia'),
                                    ('Liechtenstein'),
                                    ('Sri Lanka'),
                                    ('Liberia'),
                                    ('Lesotho'),
                                    ('Lithuania'),
                                    ('Luxembourg'),
                                    ('Latvia'),
                                    ('Libya'),
                                    ('Morocco'),
                                    ('Monaco'),
                                    ('Moldova'),
                                    ('Montenegro'),
                                    ('Saint Martin (French part)'),
                                    ('Madagascar'),
                                    ('Marshall Islands'),
                                    ('North Macedonia'),
                                    ('Mali'),
                                    ('Myanmar (Burma)'),
                                    ('Mongolia'),
                                    ('Macao'),
                                    ('Northern Mariana Islands'),
                                    ('Martinique'),
                                    ('Mauritania'),
                                    ('Montserrat'),
                                    ('Malta'),
                                    ('Mauritius'),
                                    ('Maldives'),
                                    ('Malawi'),
                                    ('Mexico'),
                                    ('Malaysia'),
                                    ('Mozambique'),
                                    ('Namibia'),
                                    ('New Caledonia'),
                                    ('Niger'),
                                    ('Norfolk Island'),
                                    ('Nigeria'),
                                    ('Nicaragua'),
                                    ('Netherlands'),
                                    ('Norway'),
                                    ('Nepal'),
                                    ('Nauru'),
                                    ('Niue'),
                                    ('New Zealand'),
                                    ('Oman'),
                                    ('Panama'),
                                    ('Peru'),
                                    ('French Polynesia'),
                                    ('Papua New Guinea'),
                                    ('Philippines'),
                                    ('Pakistan'),
                                    ('Poland'),
                                    ('Saint Pierre and Miquelon'),
                                    ('Pitcairn Islands'),
                                    ('Puerto Rico'),
                                    ('Palestine'),
                                    ('Portugal'),
                                    ('Palau'),
                                    ('Paraguay'),
                                    ('Qatar'),
                                    ('Réunion'),
                                    ('Romania'),
                                    ('Serbia'),
                                    ('Russia'),
                                    ('Rwanda'),
                                    ('Saudi Arabia'),
                                    ('Solomon Islands'),
                                    ('Seychelles'),
                                    ('Sudan'),
                                    ('Sweden'),
                                    ('Singapore'),
                                    ('Saint Helena'),
                                    ('Ascension Island (part of Saint Helena)'),
                                    ('Saint Helena Island'),
                                    ('Tristan da Cunha'),
                                    ('Slovenia'),
                                    ('Svalbard and Jan Mayen'),
                                    ('Slovakia'),
                                    ('Sierra Leone'),
                                    ('San Marino'),
                                    ('Senegal'),
                                    ('Somalia'),
                                    ('Suriname'),
                                    ('South Sudan'),
                                    ('São Tomé and Príncipe'),
                                    ('El Salvador'),
                                    ('Sint Maarten (Dutch part)'),
                                    ('Syria'),
                                    ('Eswatini'),
                                    ('Turks and Caicos Islands'),
                                    ('Chad'),
                                    ('Togo'),
                                    ('Thailand'),
                                    ('Tajikistan'),
                                    ('Tokelau'),
                                    ('Timor-Leste'),
                                    ('Turkmenistan'),
                                    ('Tunisia'),
                                    ('Tonga'),
                                    ('Turkey'),
                                    ('Trinidad and Tobago,'),
                                    ('Tuvalu'),
                                    ('Taiwan'),
                                    ('Tanzania'),
                                    ('Ukraine'),
                                    ('Uganda'),
                                    ('United States'),
                                    ('Uruguay'),
                                    ('Uzbekistan'),
                                    ('Saint Vincent and the Grenadines'),
                                    ('Venezuela'),
                                    ('British Virgin Islands'),
                                    ('United States Virgin Islands'),
                                    ('Vietnam'),
                                    ('Vanuatu'),
                                    ('Wallis and Futuna'),
                                    ('Samoa'),
                                    ('Kosovo'),
                                    ('Yemen'),
                                    ('Mayotte'),
                                    ('South Africa'),
                                    ('Zambia'),
                                    ('Zimbabwe');

insert into languages (name) values
                                 ('Afrikaans'),
                                 ('Albanian'),
                                 ('Amharic'),
                                 ('Arabic'),
                                 ('Armenian'),
                                 ('Azerbaijani'),
                                 ('Belarusian'),
                                 ('Bengali'),
                                 ('Bislama'),
                                 ('Bosnian'),
                                 ('Bulgarian'),
                                 ('Burmese'),
                                 ('Chichewa'),
                                 ('Chinese'),
                                 ('Comorian'),
                                 ('Creole'),
                                 ('Croatian'),
                                 ('Czech'),
                                 ('Danish'),
                                 ('Dhivehi'),
                                 ('Dutch'),
                                 ('Dzongkha'),
                                 ('English'),
                                 ('Estonian'),
                                 ('Faroese'),
                                 ('Fijian'),
                                 ('Filipino'),
                                 ('Finnish'),
                                 ('French'),
                                 ('Georgian'),
                                 ('German'),
                                 ('Greek'),
                                 ('Greenlandic'),
                                 ('Hebrew'),
                                 ('Hindi'),
                                 ('Hungarian'),
                                 ('Icelandic'),
                                 ('Indonesian'),
                                 ('Irish'),
                                 ('Italian'),
                                 ('Japanese'),
                                 ('Kazakh'),
                                 ('Khmer'),
                                 ('Kinyarwanda'),
                                 ('Kirundi'),
                                 ('Korean'),
                                 ('Kyrgyz'),
                                 ('Lao'),
                                 ('Latvian'),
                                 ('Lithuanian'),
                                 ('Luxembourgish'),
                                 ('Macedonian'),
                                 ('Malagasy'),
                                 ('Malay'),
                                 ('Maltese'),
                                 ('Marshallese'),
                                 ('Mongolian'),
                                 ('Montenegrin'),
                                 ('Māori'),
                                 ('Nepali'),
                                 ('Niuean'),
                                 ('Norwegian'),
                                 ('Pashto'),
                                 ('Persian'),
                                 ('Polish'),
                                 ('Portuguese'),
                                 ('Romanian'),
                                 ('Russian'),
                                 ('Samoan'),
                                 ('Serbian'),
                                 ('Sinhala'),
                                 ('Slovak'),
                                 ('Slovenian'),
                                 ('Somali'),
                                 ('Spanish'),
                                 ('Swahili'),
                                 ('Swazi'),
                                 ('Swedish'),
                                 ('Tajik'),
                                 ('Tetum'),
                                 ('Thai'),
                                 ('Tigrinya'),
                                 ('Tongan'),
                                 ('Turkish'),
                                 ('Turkmen'),
                                 ('Tuvaluan'),
                                 ('Ukrainian'),
                                 ('Urdu'),
                                 ('Uzbek'),
                                 ('Vietnamese');